### ISSUE TITLE
Comments on change.org petition?

### ISSUE THREAD

**Issue by scripting** [scripting/open-source-writing#1]
Post a reply here if you have a comment re the [text of the petition](https://github.com/scripting/open-source-writing/blob/master/2017/12/petition.md).

**Comment by jswright61** [comment]
I think leave the editorializing out, stick to the facts. Imho, this will only be effective if it gets widespread support (Rs & Ds), and in order to get Rs to sign, it will have to be less accusatory.

**Comment by frankleahy3** [comment]
Change "president" to "President", "apparently" to "possibly", "We need to" to "We the People of the United States deserved to"

**Comment by scripting** [comment]
1. https://writingexplained.org/ap-style/ap-style-president

2. why?

3. why?

**Comment by frankleahy3** [comment]
1. ok
2. Not sure it's as visible as "apparently" suggests
    - apparently: readily seen; exposed to sight; open to view; visible:
    - possibly: denote the possibility and likeliness of something being true, but there is uncertainty and doubt
3. Who does "We" refer to?  "We the People" or "We the undersigned"?  Or is it really "I", as in "I, the one who wrote this petition..."?

**Comment by scripting** [comment]
Frank, your comments raise questions of who's doing the writing and who's doing the signing. 

Re #2, I don't think there's any uncertainty as to whether the president has an improper relationship with Russia. I personally would use a stronger word. If it were just me speaking, I'd drop the word _apparently_ altogether. But to get more people to agree to it, I added _apparently,_ to express the possibility that it is just appearance. 

Re #3, _we_ refers to the people who sign the petition. It could say _we the undersigned,_ but I thought that was too fancy, too complicated, I try to go for simplicity in writing, and felt it would be understood that _we_ applied to the people who are signing the petition.

**Comment by frankleahy3** [comment]
Fair enough Dave...thanks for the back and forth.  Hope you run with it.

**Comment by scripting** [comment]
The petition is up -- 

https://www.change.org/p/americans-support-the-fbi

Dave
